### ISSUE TITLE
Installation crashing on Windows 11 because of fast_edges_extraction/_extract_edges.pyx

### ISSUE THREAD

**Issue by Theaublanchard** [scikit-shapes/scikit-shapes#46]
Hello, thanks' for the promising package. 

There seems to be an issue with the installation process on Windows : following both the installation procedure from the website or the GitHub I get the same error from pip (see stack trace below). 
The error is coming from the package `fast-edges-extraction`. Actually even installing the package alone following its github's instruction yields the same error "ValueError: 'fast_edges_extraction/_extract_edges.pyx' doesn't match any files".
Note that on linux (wsl) everything appears to be working.

PS C:\Users\inserm\Documents> pip install 'skshapes @ git+https://github.com/scikit-shapes/scikit-shapes@main'
Collecting skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main
  Cloning https://github.com/scikit-shapes/scikit-shapes (to revision main) to c:\users\inserm\appdata\local\temp\pip-install-baad2wrp\skshapes_e7b40fbb9e6f482c81a25ea361b51ac6
  Running command git clone --filter=blob:none --quiet https://github.com/scikit-shapes/scikit-shapes 'C:\Users\inserm\AppData\Local\Temp\pip-install-baad2wrp\skshapes_e7b40fbb9e6f482c81a25ea361b51ac6'
  Resolved https://github.com/scikit-shapes/scikit-shapes to commit dfaa3b619911a9b01bb6fe2168b4a130178d84a8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torch in c:\users\inserm\appdata\local\programs\python\python311\lib\site-packages (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main) (2.1.2+cu118)
Collecting torchdiffeq (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main)
  Using cached torchdiffeq-0.2.3-py3-none-any.whl.metadata (488 bytes)
Requirement already satisfied: numpy in c:\users\inserm\appdata\local\programs\python\python311\lib\site-packages (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main) (1.26.2)
Collecting pykeops (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main)
  Using cached pykeops-2.2.2.tar.gz (92 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting geomloss (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main)
  Using cached geomloss-0.2.6.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting jaxtyping (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main)
  Using cached jaxtyping-0.2.28-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: beartype==0.17.2 in c:\users\inserm\appdata\local\programs\python\python311\lib\site-packages (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main) (0.17.2)
Collecting pyvista (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main)
  Using cached pyvista-0.43.5-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: vedo in c:\users\inserm\appdata\local\programs\python\python311\lib\site-packages (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main) (2024.5.1)
Collecting fast-simplification (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main)
  Using cached fast_simplification-0.1.7-cp311-cp311-win_amd64.whl.metadata (10 kB)
Collecting fast-edges-extraction (from skshapes@ git+https://github.com/scikit-shapes/scikit-shapes@main)
  Using cached fast_edges_extraction-0.1.1.tar.gz (158 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "C:\Users\inserm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\inserm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\inserm\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\inserm\AppData\Local\Temp\pip-build-env-emxwwdqb\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\inserm\AppData\Local\Temp\pip-build-env-emxwwdqb\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\inserm\AppData\Local\Temp\pip-build-env-emxwwdqb\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
        File "C:\Users\inserm\AppData\Local\Temp\pip-build-env-emxwwdqb\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\inserm\AppData\Local\Temp\pip-build-env-emxwwdqb\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\inserm\AppData\Local\Temp\pip-build-env-emxwwdqb\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'fast_edges_extraction/_extract_edges.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by Louis-Pujol** [comment]
Hi @Theaublanchard,

We are not targeting Windows compatibility for now, mainly because we are using KeOps and it is not available on Windows. I'll add a line to the installation instructions to make it clear. We were talking recently about the possibility to make the KeOps dependency optional, if we do so I think it will be possible to install scikit-shapes on windows. I'll let you know for any updates in that direction.

For `fast-edges-extraction`, I didn't make the effort to publish a windows version whereas it should not be so difficult to do so. I'll work on it if we decide to publish a windows version.

Thanks for the feedback on wsl, it should be a good option for windows users at the moment.

**Comment by Theaublanchard** [comment]
Hi, thanks for the update. Keep up the great work!

**Comment by Louis-Pujol** [comment]
Thank you @Theaublanchard

**Comment by falsetry1514** [comment]
I also met this similiar problem in macos,
my error report is:
Traceback (most recent call last):
        File "/Users/server3/miniforge3/envs/spacoord/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/Users/server3/miniforge3/envs/spacoord/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/server3/miniforge3/envs/spacoord/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4q/mx7bngj10x9f7kh5dv6rzs5c0000gn/T/pip-build-env-d6novl02/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4q/mx7bngj10x9f7kh5dv6rzs5c0000gn/T/pip-build-env-d6novl02/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4q/mx7bngj10x9f7kh5dv6rzs5c0000gn/T/pip-build-env-d6novl02/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
        File "/private/var/folders/4q/mx7bngj10x9f7kh5dv6rzs5c0000gn/T/pip-build-env-d6novl02/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4q/mx7bngj10x9f7kh5dv6rzs5c0000gn/T/pip-build-env-d6novl02/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/4q/mx7bngj10x9f7kh5dv6rzs5c0000gn/T/pip-build-env-d6novl02/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'fast_edges_extraction/_extract_edges.pyx' doesn't match any files
How to figure it out? Thanks for help!
